"""empty message

Revision ID: f3acab076e01
Revises: 92dbdb55ef2e
Create Date: 2021-12-25 14:06:24.342837

"""

# revision identifiers, used by Alembic.
revision = 'f3acab076e01'
down_revision = '92dbdb55ef2e'

from alembic import op
import sqlalchemy as sa
from datetime import datetime


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
    
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_roles_default'), table_name='roles')
    #op.drop_column('roles', 'premissions')
    # ### end Alembic commands ###
    pass
   
